name: Sync Repos

on:
  schedule:
    - cron: '5 4,16 * * *' # at 4:05 AM and 4:05 PM everyday
  workflow_dispatch: # on button click
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      - name: Mirror the Github immortalwrt repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/immortalwrt
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          account_type: org
          force_update: false
          # debug: true
          mappings: "luci=>immortalwrt-luci,packages=>immortalwrt-packages"
          white_list: "luci,packages,immortalwrt"
      - name: Mirror the Github coolsnowwolf repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/coolsnowwolf
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          src_account_type: user  # the src account type
          dst_account_type: org  # the dst account type
          force_update: false
          debug: true
          mappings: "lede=>lean-lede"
          white_list: "lede"
