name: Sync Repos

on:
  push:
    paths:
    - '.github/workflows/**'
  schedule:
    - cron: '5 4 * * *' # at 4:05 AM everyday
  workflow_dispatch: # on button click
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      - name: Mirror the Github immortalwrt repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/immortalwrt
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          account_type: org
          force_update: false
          #debug: true
          mappings: "luci=>immortalwrt-luci,packages=>immortalwrt-packages"
          white_list: "luci,packages,immortalwrt"
      - name: Mirror the Github coolsnowwolf repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/coolsnowwolf
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          src_account_type: user  # the src account type
          dst_account_type: org  # the dst account type
          force_update: false
          #debug: true
          mappings: "lede=>lean-openwrt"
          white_list: "lede"
      - name: Mirror the Github Lienol repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/Lienol
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          src_account_type: user  # the src account type
          dst_account_type: org  # the dst account type
          force_update: false
          #debug: true
          mappings: "openwrt=>lienol-openwrt,openwrt-package=>lienol-openwrt-package"
          static_list: "openwrt,openwrt-package"
      - name: Mirror the Github kiddin9 repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/kiddin9
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          src_account_type: user  # the src account type
          dst_account_type: org  # the dst account type
          force_update: true
          #debug: true
          mappings: "openwrt-packages=>kiddin9-openwrt-packages,my-packages=>kiddin9-my-packages"
          static_list: "openwrt-packages,my-packages"
      - name: Mirror the Github 281677160 repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/281677160
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          src_account_type: user  # the src account type
          dst_account_type: org  # the dst account type
          force_update: true
          #debug: true
          mappings: "openwrt-package=>281677160-openwrt-package"
          static_list: "openwrt-package"
      - name: Mirror the Github QinLong-doc repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/Oreomeow
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          src_account_type: user  # the src account type
          dst_account_type: org  # the dst account type
          force_update: false
          #debug: true
          mappings: "vip=>qinglong-oreomeow-vip"
          static_list: "vip"
      - name: Mirror the Github QinLong repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/whyour
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          src_account_type: user  # the src account type
          dst_account_type: org  # the dst account type
          force_update: false
          #debug: true
          mappings: "qinglong=>qinglong"
          static_list: "qinglong"
      - name: Mirror the Github QinLong-fake repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/shufflewzc
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          src_account_type: user  # the src account type
          dst_account_type: org  # the dst account type
          force_update: false
          #debug: true
          mappings: "faker=>qinglong-faker,faker2=>qinglong-faker2,faker3=>qinglong-faker3,nvjdc=>qinglong-nvjdc,smeik2221backup=>qinglong-smeik2221backup"
          static_list: "faker,faker2,faker3,nvjdc,smeik2221backup"
      - name: Mirror the Github QinLong-denpendency repos
        uses: snowyu/hub-mirror-action@master
        with:
          src: github/FlechazoPh
          dst: github/mopenwrt
          dst_key: ${{ secrets.GIT_KEY }}
          dst_token: ${{ secrets.PERSONAL_TOKEN }}
          src_account_type: user  # the src account type
          dst_account_type: org  # the dst account type
          force_update: false
          #debug: true
          mappings: "QLDependency=>qinglong-dependency"
          static_list: "QLDependency"
          
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
